language: ruby

install: true
script: true

env:
  # BOXFUSE_USER=[boxfuse user]
  - secure: "kwvAcjVm71MO6682XLxpwv2hmlNzplfDS116CDJUQ3QQzHg0olSv/bSkp0aCEmDDCsqVPnmEABNSnAP7Y6fddG6dRAFY2D93/JRpeLo3kfUAubckx7v9sCJz+xPRyUyVZIhfjFcjJ3xKoVJ14NdO1lICNA6gL/F1XYkll8xlHSw="
  # BOXFUSE_SECRET=[boxfuse secret]
  - secure: "BWNbYYMLWPOe+eMkXayY9Xl/S3fR6QCBYJn826qJdZzgAXwvE8kl5Hgnac0f3X+tYsn4pSNSM4QuAm/vmMLxQNzlfcw4FDFNlIo2GIxzTwlOR8rCDpmTmxBSK0uomMcpaKxqkuqbUJmos0Ttm+Vh0vxw8/hZ55TTEXbL+b9ShkY="

before_deploy:
  - .travis/providers/boxfuse/prepare
  - cd tmp/dpl_test

deploy:
  - provider: boxfuse
    user:
      secure: "TmfDWdpCryBNzDEiPwMdjQQt9IE1Pt8L7VMF597YjWl1xC2OAFvxQ5hk7gqDioYPz2/5xzMfLdRuyejcL9u6QQxMuCgHhfadJn6dwnhbO6uR9x72KY6FLXL5bsW/+XQTS+HwUvGq7xwka7An8QNUGMsFfvdHy5VZT5qRvPVWIN4="
    secret:
      secure: "pSNJxd9xH+4EZ+0cHCqsgyjzLyI/hZK7g3SdPGqcQu90EOD6qzm1ET9Wt8eYWAxruKf8o03rEwKfAEdk84N36JxH+57AVLQh2UUM2+jjovXL8VDvpbekbXxisT4TKpzL7fxNpY+/4gkDPnJz/7g9sFbc9WO5ntOBsn7d+vT/FqQ="
    env: prod
    payload: dpl_test
    configfile: boxfuse.conf

after_deploy:
  - ../../.travis/providers/boxfuse/test || TRAVIS_TEST_RESULT=$?
  - boxfuse/boxfuse kill dpltest -env=prod
  - boxfuse/boxfuse rm
