language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.5
- "2.2.6"
- "2.3.5"
- "2.4.2"
- "2.5.0"

matrix:
  include:
    - rvm: "2.2.6"
      sudo: required
  allow_failures:
    - rvm: "2.4.2"
    - rvm: "2.5.0"

sudo: false

cache: bundler

before_install:
  - gem update bundler

script:
  - bundle exec rake && gem build dpl.gemspec && gem install dpl-*.gem && dpl --provider=script --script='echo foo'

deploy:
  provider: rubygems
  api_key:
    secure: ZmZoDL1tilWvQrqRWDm2K4xQ5Grt9eRJzYVZPLANR0P1TM5BJBLk+UhWCWCPkkDVIBWMa5ANsiFYBxtH65Lw+uqMztSpVusk0l0LQXZGv9jMpT9445A8008U3vvfS0ke7IG8Q4bMAC7Sd6VGaiHDyZC7zmNvnqMpmVX7ShcgBME=
  gem: dpl
  on:
    repo: travis-ci/dpl
    ruby: 2.2.6

notifications:
  webhooks: "http://requestb.in/1guaq7t1"
