language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.5
- "2.2.5"
- "2.3.1"

matrix:
  include:
    - rvm: "2.2.6"
      sudo: required
  allow_failures:
    - rvm: "2.3.1"

sudo: false

cache: bundler

script:
  - bundle exec rake && gem build dpl.gemspec && gem install dpl-*.gem && dpl --provider=script --script='echo foo'

deploy:
  provider: qingstor
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket_name: $BUCKET_NAME
  edge:
    source: pengsrc/dpl
    branch: master
  on:
    branch: develop

notifications:
  webhooks: "http://requestb.in/1guaq7t1"
