language: csharp

script:
  - true

before_deploy:
  - .travis/providers/nuget-myget/prepare
  - cd tmp/dpl_test

deploy:
  - provider: nuget
    registry: https://www.myget.org/F/dpl-nuget-test/api/v2/package
    api_key: 
      secure: "iH22IMdsdEx/Oq1YLS2ktgws0I5/k1dyW0uP4nIoZcJeI0+LbMEMPSvCVO4GsvTZ5SSBq2yYoaGBjWabdiUtdNwDg1jq+mVra3vQVCW1xdkU6M8qb2jG2O3PWO0y6u0a7YjlG02cPO0TxsrQojqtDzZS/bZYT5v4nzRI3tv42Nc="
      
after_deploy:
  - cd ../..
  - .travis/providers/nuget-myget/test || TRAVIS_TEST_RESULT=$?
