language: shell

env:
  - secure: "RIHfGfsaXpGKD/4JoOqLSz+BdD02GU3l730FoItRPyP+/6/if3c00LW8MkxeHitQOOBS97492GOQtLa0l1pZ+W4eiIvl3fLYbzKGep+EV5F05fZF8koOeUdcYdiLPnMVsmkgY0YzHInI6edsgbfyrlvdIw3mWszkCFhWkpKW86A="
  - secure: "l7pvhRR8o/ziU3vgnAcwmg7UoVy2yEdVdJ3eip3FeKpy4f1BWhjR0RC2psSe6HTdUb/AzKSN3o+IGrycAc9oVXgVSa/dmjDnB55N/GddI/vkB9I2qDPc419OhAd2rUkJxS1qKMT70U2B2fLVYtAFF0nw11xAGIX7Ik1kmkcHoQQ="

script:
  - true

before_deploy:
  - .travis/providers/aws-lambda/prepare
  - cd tmp/dpl_test

deploy:
  - provider: lambda
    skip_cleanup: true

    # dpl_test
    access_key_id:
      secure: "b8BMnGujyCJHcOpG1lS5w/b7MeL9dFo87LIodMv0/dn6fWIIfPbWVzK8A0ZEGGiYskJ89vZtfMwB2X5NzWlob3UJvDhEOGTaCUPoQDHlRtwVXL0HG5k6a2i6DJ7P24OdHe7t64Lxota3lGt4pESa7Js08GEjrjaQc7oyGcS5hX4="
    secret_access_key:
      secure: "dEg7g2CzQRGw/Ao0w9TW2lFQJUFnL9ou2DMCZqnlauJircy8VWNbY2oqbe4yqkyFkr9VmXEF7zCtiSlZm/RwYHbAH3unuw2a7/3M6fw3jcSIrMA3I0TAlLPt0HGF4Ohu8jPQLy2wq26WE/71vIoEIuVUxJAmx5I6z4+B4L0jBIQ="

    region: eu-central-1
    function_name: dpl-test
    role: arn:aws:iam::341288657826:role/lambda_basic_execution
    handler_name: handler
    zip: index.js

after_deploy:
  - cd ../..
  # - gem install aws-sdk --version '~> 2.0'
  - gem install aws-sdk-lambda
  - .travis/providers/aws-lambda/test || TRAVIS_TEST_RESULT=$?
