language: shell

script:
  - true

before_deploy:
  - mkdir -p tmp/dpl_test
  - openssl aes-256-cbc -K $encrypted_81cf70da4be5_key -iv $encrypted_81cf70da4be5_iv -in .travis/providers/chef_supermarket/private_key.enc -out tmp/dpl_test/private_key -d
  - .travis/providers/chef_supermarket/prepare
  - cd tmp/dpl_test

deploy:
  - provider: chef_supermarket

    user_id: dpl-test
    client_key: private_key
    cookbook_name: dpl_test
    cookbook_category: Other

after_deploy:
  - cd ../..
  - .travis/providers/chef_supermarket/test || TRAVIS_TEST_RESULT=$?
